# Generated by Django 4.2 on 2023-05-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'enpoints',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.endpoint')),
            ],
            options={
                'db_table': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.endpoint')),
            ],
            options={
                'db_table': 'schemas',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.schema')),
            ],
            options={
                'db_table': 'markers',
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.service'),
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.endpoint')),
            ],
            options={
                'db_table': 'contexts',
            },
        ),
    ]
