# Generated by Django 4.2 on 2023-05-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table='endpoints',
        ),
    ]
