# Generated by Django 4.2.1 on 2023-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_api', '0007_alter_endpoint_url_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
